#!/usr/bin/env perl
use 5.10.0;
use strict;
use warnings;
use File::Basename;
use lib dirname(dirname(__FILE__)) . '/lib';
use Cwd;
use App::RepoSync::Export;
use YAML;

my ($export_file,@dirs) = @ARGV;


die 'export file is required' unless $export_file;

@dirs = getcwd() unless @dirs;

say 'scanning repos...';
my @data = ();
for( @dirs ) {
    my @repos = App::RepoSync::Export->run( $_ );
    push @data, @repos;
}

YAML::DumpFile( $export_file , {
    version => 0.1,
    repos => \@data,
});
say 'done';
